""" adding is vervied Field to user modle 

Revision ID: 17e23dd74091
Revises: 895810ef3b69
Create Date: 2026-04-02 00:19:00.938774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17e23dd74091'
down_revision: Union[str, None] = '895810ef3b69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_vervied', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_vervied')
    # ### end Alembic commands ###
