"""adding Blacklist token model to add black listed token from accessing resourses

Revision ID: 1a4b10141d26
Revises: 6e1b7192dbe3
Create Date: 2026-04-04 23:16:45.843389

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "1a4b10141d26"
down_revision: Union[str, None] = "6e1b7192dbe3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
