"""adding Blacklist token model to add black listed token from accessing resourses  

Revision ID: 46381d390cf9
Revises: 17e23dd74091
Create Date: 2026-04-04 23:04:03.993410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46381d390cf9'
down_revision: Union[str, None] = '17e23dd74091'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
