"""adding is_admin for RBCA for specify user roles in system  

Revision ID: 623698fdc1d4
Revises: ae0648166171
Create Date: 2026-05-03 23:00:38.894433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '623698fdc1d4'
down_revision: Union[str, None] = 'ae0648166171'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('avatar', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar')
    op.drop_column('users', 'is_admin')
    op.drop_column('blogs', 'image_url')
    # ### end Alembic commands ###
