"""adding Blacklist token model to add black listed token from accessing resourses  

Revision ID: 6e1b7192dbe3
Revises: be88edc40664
Create Date: 2026-04-04 23:12:29.346099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e1b7192dbe3'
down_revision: Union[str, None] = 'be88edc40664'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
