"""adding Blacklist token model to add black listed token from accessing resourses

Revision ID: be88edc40664
Revises: 46381d390cf9
Create Date: 2026-04-04 23:12:08.193522

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "be88edc40664"
down_revision: Union[str, None] = "46381d390cf9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
